=== okleine/iSenseStaticRoutingCodeGenerator/src/main/resources/static-routing.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tn="http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing"
    targetNamespace="http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing">

    <xs:complexType name="ReachableNodesType">
        <xs:sequence>
            <xs:element name="node" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RoutingEntryType">
        <xs:all>
            <xs:element name="nextHop" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="reachableNodes" type="tn:ReachableNodesType"/>
        </xs:all>
    </xs:complexType>

	<xs:complexType name="RouterConfigType">
		<xs:sequence>
            <xs:element name="router" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="defaultRoute" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="routingEntry" type="tn:RoutingEntryType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

    <xs:element name="networkRoutingConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="routerConfig" type="tn:RouterConfigType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== okleine/iSenseStaticRoutingCodeGenerator/src/main/resources/static-routing-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns:networkRoutingConfig xsi:schemaLocation="http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing static-routing.xsd"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:ns="http://www.itm.uni-luebeck.de/users/kleine/isense-static-routing">

    <!--Configuration for 0x2128-->
    <routerConfig>
        <router>2128</router>
        <defaultRoute>212c</defaultRoute>
    </routerConfig>

    <!--Configuration for 0x212c-->
    <routerConfig>
        <router>212c</router>
        <defaultRoute>2130</defaultRoute>
        <routingEntry>
            <nextHop>2128</nextHop>
            <reachableNodes>
                <node>2128</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2100</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>213c</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>

    <!--Configuration for 0x2130-->
    <routerConfig>
        <router>2130</router>
        <defaultRoute>2134</defaultRoute>
        <routingEntry>
            <nextHop>212c</nextHop>
            <reachableNodes>
                <node>2128</node>
                <node>212c</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2100</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>

    <!--Configuration for 0x2134-->
    <routerConfig>
        <router>2134</router>
        <defaultRoute>158d0000144246</defaultRoute>
        <routingEntry>
            <nextHop>2130</nextHop>
            <reachableNodes>
                <node>2128</node>
                <node>212c</node>
                <node>2130</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2138</nextHop>
            <reachableNodes>
                <node>2138</node>
                <node>213c</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2104</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x001507201001-->
    <routerConfig>
        <router>158d0000144246</router>
        <defaultRoute>null</defaultRoute>
        <routingEntry>
            <nextHop>2134</nextHop>
            <reachableNodes>
                <node>2128</node>
                <node>212c</node>
                <node>2130</node>
                <node>2134</node>
                <node>2138</node>
                <node>213c</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2104</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2138-->
    <routerConfig>
        <router>2138</router>
        <defaultRoute>2134</defaultRoute>
        <routingEntry>
            <nextHop>2108</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>213c</nextHop>
            <reachableNodes>
                <node>213c</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x213c-->
    <routerConfig>
        <router>213c</router>
        <defaultRoute>2138</defaultRoute>
        <routingEntry>
            <nextHop>2110</nextHop>
            <reachableNodes>
                <node>2100</node>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2140-->
    <routerConfig>
        <router>2140</router>
        <defaultRoute>2118</defaultRoute>
        <routingEntry>
            <nextHop>2144</nextHop>
            <reachableNodes>
                <node>2144</node>
                <node>2120</node>
                <node>2124</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2144-->
    <routerConfig>
        <router>2144</router>
        <defaultRoute>2140</defaultRoute>
        <routingEntry>
            <nextHop>2120</nextHop>
            <reachableNodes>
                <node>2120</node>
                <node>2124</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2100-->
    <routerConfig>
        <router>2100</router>
        <defaultRoute>212c</defaultRoute>
        <routingEntry>
            <nextHop>2104</nextHop>
            <reachableNodes>
                <node>2104</node>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2104-->
    <routerConfig>
        <router>2104</router>
        <defaultRoute>158d0000144246</defaultRoute>
        <routingEntry>
            <nextHop>2100</nextHop>
            <reachableNodes>
                <node>2100</node>
            </reachableNodes>
        </routingEntry>
        <routingEntry>
            <nextHop>2108</nextHop>
            <reachableNodes>
                <node>2108</node>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2108-->
    <routerConfig>
        <router>2108</router>
        <defaultRoute>2104</defaultRoute>
        <routingEntry>
            <nextHop>210c</nextHop>
            <reachableNodes>
                <node>210c</node>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x210c-->
    <routerConfig>
        <router>210c</router>
        <defaultRoute>2108</defaultRoute>
        <routingEntry>
            <nextHop>2110</nextHop>
            <reachableNodes>
                <node>2110</node>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
            </reachableNodes>
        </routingEntry>
    </routerConfig>
    
    <!--Configuration for 0x2110-->
    <routerConfig>
        <router>2110</router>
        <defaultRoute>213c</defaultRoute>
        <routingEntry>
            <nextHop>2114</nextHop>
            <reachableNodes>
                <node>2114</node>
                <node>2118</node>
                <node>211c</node>
                <node>2120</node>
                <node>2124</node>
                <node>2140</node>
                <node>2144</node>
